### ISSUE TITLE
Improve Little Kai example with Kotlin implementation of Decorator

### ISSUE THREAD

**Issue by Cotel** [CloudCoders/Design-Patterns#2]
More info: https://github.com/dbacinski/Design-Patterns-In-Kotlin#decorator

**Comment by Cotel** [comment]
I've been trying to implement the example in this way and I don't think it is useful in this case.

Kotlin's `by` operator is used to _Delegate_ **properties (not methods)**

Taken from [Stack Overflow](http://stackoverflow.com/questions/38250022/what-does-by-keyword-do-in-kotlin):

> You delegate the getter/setter to another class that does the work and can contain common code.

So, in this case we should _Delegate_ the COST of all the decorators of `Noodles` to the class `IngredientDecorator` and don't use `calculateCost()`. But this cannot be possible because the **parent Decorator** doesn't know the concrete price of each **concrete Decorator**.

Please, discuss if I am right. I want to know what the author of the repository above did because I don't know if I am taking the correct approach...

**Comment by tonilopezmr** [comment]
In this case only simplified the SauceDelegator, because You don't need override this method thanks to `by` keyword that delegate to a property the super behaviour.

For example: ![](https://github.com/CloudCoders/Design-Patterns/pull/4/commits/9c90d46ae1509426bf2d5c2340ebaf25bc5ec998#diff-da0ac535b14cd13e95acd1029c62d982L3) 

You don't need override `calculateCost()` because you delegate this method to the property `val noodles: Noodles` thanks to do this `Noodles by noodles` above `noodles constructor property`

All can do `val noodles: Noodles` you could delegate from it.

**Comment by tonilopezmr** [comment]
For example [this example](https://github.com/dbacinski/Design-Patterns-In-Kotlin#decorator) have not sense because it's the same using `by` key word or not. 

The example is better if makeLargeCoffee() aren't implemented
